import { Platform } from 'react-native';

const DOMAIN_IOS_SELECT = "http://14.160.26.131:8086";
const DOMAIN_IOS_INSERT = "http://14.160.26.131:8086";

const DOMAIN_ANDROID_SELECT = "http://14.160.26.131:8086";
const DOMAIN_ANDROID_INSERT = "http://14.160.26.131:8086";

export const DOMAIN_CONFIG_SELECT = Platform.OS == 'android' ? DOMAIN_ANDROID_SELECT : DOMAIN_IOS_SELECT;
export const DOMAIN_CONFIG_INSERT = Platform.OS == 'android' ? DOMAIN_ANDROID_INSERT : DOMAIN_IOS_INSERT;

export const DOMAIN_CONFIG_REPORT= 'http://14.160.26.131:8086';

export const VERSION = '0.0.1';
export const API_CONFIG = '';

export const KEY_STORAGE = {
    ISLOGIN: 'ISLOGIN',
    USERNAME: 'USERNAME',
    PASSWORD: 'PASSWORD',
    FULLNAME: 'FULLNAME',
    SHOPID: 'SHOPID',
    ROUTECODE: 'ROUTECODE',
    BRANCHCODE: 'BRANCHCODE',
    COMPANYCODE: 'COMPANYCODE',
    HAVEORDER: 'HAVEORDER',
    TOKEN: 'TOKEN',
    DEVICEID: 'DEVICEID',
    SERVER: 'SERVER',
    OS: 'OS',
    ISPHOTO: 'ISPHOTO', //true/false can phai chup hinh
    NAME_SCREEN_SELECTED: 'NAME_SCREEN_SELECTED',
    LEADER: 'LEADER',
    DATELOGIN: 'DATELOGIN',
    TYPESALE: 'TYPESALE',
};
export const EVENT = {
    ERROR: 'ERROR',
    RELOAD_EVENT_EXIBIT_LIST: 'RELOAD_EVENT_EXIBIT_LIST',
    UPDATE_ITEM_INPROGRESS: 'UPDATE_ITEM_INPROGRESS',
};

export const HOTLINE = '0354647262';